//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.233
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMBot {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCMBot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opensource Project
        ///Note: Program may contain critical bugs, for testing purposes only!
        ///Website: http://scmbot.com
        ///Copyright © 2013-2014 Maxx53
        ///
        ///
        ///Do you want to visit Github page?.
        /// </summary>
        internal static string aboutBody {
            get {
                return ResourceManager.GetString("aboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About....
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding to Sale....
        /// </summary>
        internal static string AddSell {
            get {
                return ResourceManager.GetString("AddSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already Logged.
        /// </summary>
        internal static string AlreadyLogged {
            get {
                return ResourceManager.GetString("AlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item bought.
        /// </summary>
        internal static string Bought {
            get {
                return ResourceManager.GetString("Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while buying!.
        /// </summary>
        internal static string BuyError {
            get {
                return ResourceManager.GetString("BuyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buying &quot;{0}&quot; in process....
        /// </summary>
        internal static string buyingProc {
            get {
                return ResourceManager.GetString("buyingProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language changed to .
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, Check desired Items.
        /// </summary>
        internal static string CheckIt {
            get {
                return ResourceManager.GetString("CheckIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check your values and try again..
        /// </summary>
        internal static string CheckVal {
            get {
                return ResourceManager.GetString("CheckVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=demmaxx@gmail.com&amp;lc=EN&amp;item_name=SteamCMBot%20Donate&amp;currency_code=RUB&amp;bn=PP-DonationsBF.
        /// </summary>
        internal static string donateLink {
            get {
                return ResourceManager.GetString("donateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error loading account information!.
        /// </summary>
        internal static string ErrAccInfo {
            get {
                return ResourceManager.GetString("ErrAccInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while Login: .
        /// </summary>
        internal static string ErrLogin {
            get {
                return ResourceManager.GetString("ErrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It&apos;s first time launch. Please, check settings.
        ///You can find it in system tray anytime..
        /// </summary>
        internal static string FirstTime {
            get {
                return ResourceManager.GetString("FirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found: {0}, Shown: {1}.
        /// </summary>
        internal static string FoundShown {
            get {
                return ResourceManager.GetString("FoundShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price Graph for {0}.
        /// </summary>
        internal static string GraphFor {
            get {
                return ResourceManager.GetString("GraphFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time: {0}
        ///Price: {1} {2}.
        /// </summary>
        internal static string GraphTip {
            get {
                return ResourceManager.GetString("GraphTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In Inventory ({0}).
        /// </summary>
        internal static string inInventory {
            get {
                return ResourceManager.GetString("inInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item .
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to load Inventory fist..
        /// </summary>
        internal static string LoadInvFirst {
            get {
                return ResourceManager.GetString("LoadInvFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log for this Item is Empty..
        /// </summary>
        internal static string LogEmpty {
            get {
                return ResourceManager.GetString("LogEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please login first..
        /// </summary>
        internal static string LoginFirst {
            get {
                return ResourceManager.GetString("LoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login Success.
        /// </summary>
        internal static string LoginSucc {
            get {
                return ResourceManager.GetString("LoginSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logouted.
        /// </summary>
        internal static string Logouted {
            get {
                return ResourceManager.GetString("Logouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not For Sale.
        /// </summary>
        internal static string NFS {
            get {
                return ResourceManager.GetString("NFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на is not logged.
        /// </summary>
        internal static string NotLogged {
            get {
                return ResourceManager.GetString("NotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature is not working yet..
        /// </summary>
        internal static string NotWork {
            get {
                return ResourceManager.GetString("NotWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On Sale ({0}).
        /// </summary>
        internal static string onSale {
            get {
                return ResourceManager.GetString("onSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items On sale not found!.
        /// </summary>
        internal static string OnSaleErr {
            get {
                return ResourceManager.GetString("OnSaleErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try to relogin....
        /// </summary>
        internal static string Relogin {
            get {
                return ResourceManager.GetString("Relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Sell.
        /// </summary>
        internal static string RemSell {
            get {
                return ResourceManager.GetString("RemSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removing from Sell....
        /// </summary>
        internal static string RemSellStat {
            get {
                return ResourceManager.GetString("RemSellStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items on Sale.
        /// </summary>
        internal static string SaleItems {
            get {
                return ResourceManager.GetString("SaleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan Cancelled.
        /// </summary>
        internal static string ScanCancel {
            get {
                return ResourceManager.GetString("ScanCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while scanning!.
        /// </summary>
        internal static string ScanError {
            get {
                return ResourceManager.GetString("ScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scanning Prices....
        /// </summary>
        internal static string ScanPrice {
            get {
                return ResourceManager.GetString("ScanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing found.
        /// </summary>
        internal static string SearchErr {
            get {
                return ResourceManager.GetString("SearchErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell Checked.
        /// </summary>
        internal static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item(s) removed from Sell.
        /// </summary>
        internal static string SellRemoved {
            get {
                return ResourceManager.GetString("SellRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try Login....
        /// </summary>
        internal static string tryLogin {
            get {
                return ResourceManager.GetString("tryLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Try to find and choose an Item first!.
        /// </summary>
        internal static string TryToFind {
            get {
                return ResourceManager.GetString("TryToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown Error.
        /// </summary>
        internal static string UnknownErr {
            get {
                return ResourceManager.GetString("UnknownErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wait....
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price format is invalid!.
        /// </summary>
        internal static string WrongPrice {
            get {
                return ResourceManager.GetString("WrongPrice", resourceCulture);
            }
        }
    }
}
